name: Build SMTP Relay

on: [push]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Service
        run: dotnet publish ./src/SmtpRelay/SmtpRelay.csproj -c Release -o ./installer/output/service

      - name: Build GUI
        run: dotnet publish ./src/SmtpRelay.GUI/SmtpRelay.GUI.csproj -c Release -o ./installer/output/gui

      - name: Install Inno Setup
        run: choco install innosetup --no-progress

      - name: Build Installer
        working-directory: installer
        run: '& "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "SmtpRelayInstaller.iss"'

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: smtp-relay-installer
          path: installer/SmtpRelaySetup.exe