name: Build and Package Installer

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish Windows Service
        run: dotnet publish ./src/SmtpRelay/SmtpRelay.csproj -c Release -o installer/output/service

      - name: Publish GUI
        run: dotnet publish ./src/SmtpRelay.GUI/SmtpRelay.GUI.csproj -c Release -o installer/output/gui

      - name: Compile Installer with Inno Setup
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "installer\SmtpRelayInstaller.iss"

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: smtp-relay-setup
          path: installer/SmtpRelaySetup.exe
