
name: Build and Package Installer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-installer:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore and Build Service
        run: dotnet publish ./src/SmtpRelay/SmtpRelay.csproj -c Release -o ./output

      - name: Restore and Build GUI
        run: dotnet publish ./src/SmtpRelay.GUI/SmtpRelay.GUI.csproj -c Release -o ./output

      - name: Install Inno Setup
        run: choco install innosetup --yes

      - name: Build Installer
        shell: pwsh
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "installer\SmtpRelayInstaller.iss"

      - name: Upload Final Installer
        uses: actions/upload-artifact@v4
        with:
          name: smtp-relay-setup
          path: installer/SmtpRelaySetup.exe
