name: Build and Package Installer

on:
  push:
    branches: [ main ]

jobs:
  build-installer:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore and Build Service
      run: dotnet publish ./src/SmtpRelay/SmtpRelay.csproj -c Release -o ./output

    - name: Restore and Build GUI
      run: dotnet publish ./src/SmtpRelay.GUI/SmtpRelay.GUI.csproj -c Release -o ./output

    - name: Install Inno Setup
      run: choco install innosetup --yes

    - name: Build Installer
      run: '"C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer\SmtpRelayInstaller.iss'

    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: SmtpRelaySetup
        path: SmtpRelaySetup.exe
