name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-release:
    uses: ./.github/workflows/build.yml

  upload-release:
    needs: build-release
    runs-on: ubuntu-latest
    steps:
    - name: Download installer artifact
      uses: actions/download-artifact@v4
      with:
        name: SmtpRelaySetup

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        body: |
          Automated release for ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Asset
      uses: softprops/action-gh-release@v2
      with:
        files: SmtpRelaySetup.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}